// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDvSN-4uBhx7OM6Qsvu4bYZ5tcECJ9aAA',
    appId: '1:92715321903:web:1849665ddf719bd6cb94da',
    messagingSenderId: '92715321903',
    projectId: 'remedic-23769',
    authDomain: 'remedic-23769.firebaseapp.com',
    storageBucket: 'remedic-23769.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvp7UsyyyXwAEWne1XfqIyy1FNIUsMe2A',
    appId: '1:92715321903:android:ac865b49d84a33bccb94da',
    messagingSenderId: '92715321903',
    projectId: 'remedic-23769',
    storageBucket: 'remedic-23769.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLngywFNOGharKffMlmhM0ZgADNEsOBPg',
    appId: '1:92715321903:ios:6dfb0c6731d77ccacb94da',
    messagingSenderId: '92715321903',
    projectId: 'remedic-23769',
    storageBucket: 'remedic-23769.firebasestorage.app',
    iosBundleId: 'com.example.remedic',
  );

}